"""
generate_insert_sql.py
MSc Thesis Prototype

Run locally (not in Supabase):
    python generate_insert_sql.py

Reads product_info_sample.csv and writes load_products.sql —
a single SQL file with batched INSERT statements ready to paste
into the Supabase SQL Editor (or run via psql).

Usage:
    python generate_insert_sql.py --csv product_info_sample.csv --out load_products.sql
"""

import csv
import ast
import json
import argparse
import sys
from pathlib import Path


def parse_bool(val: str) -> bool:
    return str(val).strip() in ("1", "true", "True", "TRUE", "yes")


def parse_float(val: str):
    v = val.strip()
    if v == "" or v is None:
        return "NULL"
    try:
        return str(float(v))
    except ValueError:
        return "NULL"


def parse_int(val: str):
    v = val.strip()
    if v == "":
        return "NULL"
    try:
        return str(int(float(v)))
    except ValueError:
        return "NULL"


def escape(val: str) -> str:
    """Escape single quotes for SQL string literals."""
    return val.replace("'", "''") if val else ""


def parse_highlights(val: str) -> str:
    """
    The highlights column is a Python list literal.
    Normalise to a JSON array string.
    Returns SQL-safe quoted string, or NULL.
    """
    v = val.strip()
    if not v:
        return "NULL"
    try:
        parsed = ast.literal_eval(v)
        if isinstance(parsed, list):
            return f"'{escape(json.dumps(parsed))}'"
    except Exception:
        pass
    return f"'{escape(v)}'"


def parse_ingredients(val: str) -> str:
    """
    Ingredients is either a plain string or a Python list literal.
    Flatten list to comma-separated string.
    """
    v = val.strip()
    if not v:
        return "NULL"
    try:
        parsed = ast.literal_eval(v)
        if isinstance(parsed, list):
            flat = " ".join(str(x) for x in parsed)
            return f"'{escape(flat)}'"
    except Exception:
        pass
    return f"'{escape(v)}'"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", default="product_info_sample.csv",
                        help="Path to the Sephora product CSV")
    parser.add_argument("--out", default="load_products.sql",
                        help="Output SQL filename")
    parser.add_argument("--batch", type=int, default=200,
                        help="Rows per INSERT statement (default 200)")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"ERROR: CSV file not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    print(f"Loaded {len(rows)} rows from {csv_path}")

    sql_lines = [
        "-- Auto-generated by generate_insert_sql.py",
        "-- Paste into Supabase SQL Editor AFTER running migrate_to_real_products.sql",
        "",
        "INSERT INTO products (",
        "    id, product_name, brand_id, brand_name,",
        "    loves_count, rating, review_count,",
        "    size, variation_type, variation_value, variation_desc,",
        "    ingredients, price_usd, value_price_usd, sale_price_usd,",
        "    limited_edition, is_new, online_only, out_of_stock, sephora_exclusive,",
        "    highlights, primary_category, secondary_category, tertiary_category,",
        "    child_count, child_max_price, child_min_price",
        ") VALUES",
    ]

    value_rows = []

    for r in rows:
        pid = r.get("product_id", "").strip()
        if not pid:
            continue  # skip rows without a product ID

        parts = (
            f"    ("
            f"'{escape(pid)}', "
            f"'{escape(r.get('product_name',''))}', "
            f"{parse_int(r.get('brand_id',''))}, "
            f"'{escape(r.get('brand_name',''))}', "
            f"{parse_int(r.get('loves_count',''))}, "
            f"{parse_float(r.get('rating',''))}, "
            f"{parse_int(r.get('reviews',''))}, "
            f"'{escape(r.get('size',''))}', "
            f"'{escape(r.get('variation_type',''))}', "
            f"'{escape(r.get('variation_value',''))}', "
            f"'{escape(r.get('variation_desc',''))}', "
            f"{parse_ingredients(r.get('ingredients',''))}, "
            f"{parse_float(r.get('price_usd',''))}, "
            f"{parse_float(r.get('value_price_usd',''))}, "
            f"{parse_float(r.get('sale_price_usd',''))}, "
            f"{'TRUE' if parse_bool(r.get('limited_edition','')) else 'FALSE'}, "
            f"{'TRUE' if parse_bool(r.get('new','')) else 'FALSE'}, "
            f"{'TRUE' if parse_bool(r.get('online_only','')) else 'FALSE'}, "
            f"{'TRUE' if parse_bool(r.get('out_of_stock','')) else 'FALSE'}, "
            f"{'TRUE' if parse_bool(r.get('sephora_exclusive','')) else 'FALSE'}, "
            f"{parse_highlights(r.get('highlights',''))}, "
            f"'{escape(r.get('primary_category',''))}', "
            f"'{escape(r.get('secondary_category',''))}', "
            f"'{escape(r.get('tertiary_category',''))}', "
            f"{parse_int(r.get('child_count',''))}, "
            f"{parse_float(r.get('child_max_price',''))}, "
            f"{parse_float(r.get('child_min_price',''))}"
            f")"
        )
        value_rows.append(parts)

    # Write in batches (Supabase SQL editor has a payload limit)
    batch = args.batch
    output_lines = [
        "-- Auto-generated by generate_insert_sql.py",
        f"-- {len(value_rows)} products from {csv_path.name}",
        "-- Run AFTER migrate_to_real_products.sql",
        "",
    ]

    for i in range(0, len(value_rows), batch):
        chunk = value_rows[i : i + batch]
        output_lines.append(
            "INSERT INTO products (\n"
            "    id, product_name, brand_id, brand_name,\n"
            "    loves_count, rating, review_count,\n"
            "    size, variation_type, variation_value, variation_desc,\n"
            "    ingredients, price_usd, value_price_usd, sale_price_usd,\n"
            "    limited_edition, is_new, online_only, out_of_stock, sephora_exclusive,\n"
            "    highlights, primary_category, secondary_category, tertiary_category,\n"
            "    child_count, child_max_price, child_min_price\n"
            ") VALUES\n"
            + ",\n".join(chunk)
            + "\nON CONFLICT (id) DO UPDATE SET\n"
            "    product_name       = EXCLUDED.product_name,\n"
            "    rating             = EXCLUDED.rating,\n"
            "    loves_count        = EXCLUDED.loves_count,\n"
            "    review_count       = EXCLUDED.review_count,\n"
            "    price_usd          = EXCLUDED.price_usd,\n"
            "    highlights         = EXCLUDED.highlights,\n"
            "    primary_category   = EXCLUDED.primary_category,\n"
            "    secondary_category = EXCLUDED.secondary_category,\n"
            "    tertiary_category  = EXCLUDED.tertiary_category;\n"
        )

    out_path = Path(args.out)
    out_path.write_text("\n".join(output_lines), encoding="utf-8")
    print(f"Written {len(value_rows)} product inserts → {out_path}")
    print(f"Batches of {batch}: {len(value_rows)//batch + 1} INSERT statements")


if __name__ == "__main__":
    main()
